name: value_extensions
description: Set of extensions on ValueListenable that allows to use it as Streams in the Rx way.
version: 0.1.0
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/LooksGoodApp/flutter-value-extensions

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.5
