publish_to: "none"
name: value_extensions
description: Set of extensions on ValueNotifier that allows to use it as Streams in the Rx way.
version: 0.0.1
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/LooksGoodApp/flutter-value-extensions

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.5
